----------------------marketing_summary_view.sql--------------------------------
CREATE OR REPLACE VIEW VW_MARKETING_SUMMARY AS
SELECT
    A.CHANNEL,
    SUM(A.SPEND) AS TOTAL_SPEND,
    SUM(C.REVENUE) AS TOTAL_REVENUE,
    ROUND(SUM(C.REVENUE) / SUM(A.SPEND), 2) AS ROAS,
    ROUND(SUM(A.SPEND) / COUNT(DISTINCT C.USER_ID), 2) AS CAC
FROM AD_SPEND A
JOIN USER_JOURNEY U
    ON A.CAMPAIGN = U.CAMPAIGN
JOIN CONVERSIONS C
    ON U.USER_ID = C.USER_ID
GROUP BY A.CHANNEL;

SELECT VIEW_NAME
FROM USER_VIEWS
ORDER BY VIEW_NAME;